# Server
server.port=8002

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27018/restaurant_db}

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql



# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.jpa.open-in-view=false

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


